### ISSUE TITLE
Multifox Multiple Sessions Per Tab

### ISSUE THREAD

**Issue by gaspower** [hultmann/multifox#120]
Hello,

I just installed Multifox version 1.38, and version 22 of FF. I am having trouble with Multifox working in each tab. It wants to create a new FF page each time. Is there a way to make Multifox work with each tab. I manage a few different Ebay sites and would like to have each user in a unique tab.

Thanks JR

**Comment by hultmann** [comment]
sorry, each window can have only one ebay login and it's not possible to change that.

**Comment by hultmann** [comment]
Having said that, I'm considering adding this feature. I'll wait for some feedback of version 2.0.

**Comment by nhantrn** [comment]
wait...how is it possible per tab?

**Comment by Drugoy** [comment]
@hultmann I don't get why you are considering this or why you keep maintaining v1 at all:
IMO v2 has more features and generally works way better, since it provides way more capabilities (though it's quite buggy at the moment).
Shouldn't you just slowly port ALL the things from v2 to v1 and thus just fix v2's bugs and finally release it as the main version now?

**Comment by LordJZ** [comment]
Please don't drop v1 though. I like the more deterministic way of switching cookie sets for all the websites which v1 has to offer.
