### ISSUE TITLE
'Open in a new identity profile' not working like it used to

### ISSUE THREAD

**Issue by kcriqui** [hultmann/multifox#150]
Firefox 29.0.1. When I right click on a tab and select "Open in a new identity profile", it used to re-open the tab in the next existing profile number.  For example, if I was in the primary profile, the tab would be re-opened in profile #2. Now when I do this, a new profile is created and the tab opened in that.  For example, I have only one window / tab open and "Open in a new identity profile" re-opens the tab in profile #3.  Done again, with no other windows, tabs or profiles open, the tabe is re-opened in profile #4.

**Comment by fcmerlin** [comment]
Hi! This is a feature, not a bug. The Multifox author intentionally made this change due to feed back from someone else. See closed issue: https://github.com/hultmann/multifox/issues/127

On one hand, I LOVE the new functionality. I use 20 profiles on a regular basis, and it was inconvenient to have to open 20 profiles before I could get a fresh profile with no existing cookies.

On the other hand, I also need the old functionality. When I need to use all 20 profiles at the same time, I used to use AppleScript select "New Identity Profile" to bring them up. In this new functionality, I have to go and select each of the 20 profiles from the menu to open them. It's a lot of mousing to do that.

It'd be great if we can have both the current "New Identity Profile" as well as a "Next Identity Profile" that has the old functionality.

**Comment by kcriqui** [comment]
I agree, an 'open in next profile' which works the same as 'open in new profile' used to would be nice.  Perhaps a pulldown so that people can open a new link/tab/window in any existing profile would be helpful.

**Comment by hultmann** [comment]
How about replacing the current link/tab command by a drop down menu?

Open in another profile |> [New / Default / Private / 1 / 2 / 3]

**Comment by hultmann** [comment]
Now Multifox profiles are per-tab, tab strip menuitem lost its value. So I'm removing the command.

This bug is about fixing "Open Link in New Identity Profile".

**Comment by hultmann** [comment]
Please try:
https://github.com/hultmann/multifox/releases/download/2.2.0/multifox-3.0.0b1.xpi

**Comment by ciuly** [comment]
not working right. It has the exact same menu entries as release version, but the menu window is as tall as my screen and is all empty. I restarted FF, same thing.
![screen14](https://cloud.githubusercontent.com/assets/8802041/4308787/403889a2-3e96-11e4-83f4-2a2259d75e79.PNG)

edit: after clicking on the "new" button, it opened the next profile, in the current tab. This is cool but was unexpected. Now that I re-read the previous comments, I should have seen it coming.
But, the new/next profile is added to the above list (in between the already shown 2 items) and the menu window is shrunk to fit them 3. That's it. The context menu also shows only those 3 profiles.
