### ISSUE TITLE
There's a bug on this last version

### ISSUE THREAD

**Issue by M4CC** [hultmann/multifox#213]
Hello, I have a bug on the latest version of the plug-in where when I open a new profile I only get the first two tabs as part of the profile and then the 3rd and following tabs within that window revert back to the default profile.

Are you guys aware of this bug? How can I help troubleshoot this in order to get it fixed?

Thanks!

**Comment by hultmann** [comment]
latest version = 3.2.1? Not sure if it is #207.

**Comment by yazhog** [comment]
Join us.
This problem is at version 3.2.1 and earlier.
I checked all versions since 3.0.

I work in multiple windows with different profiles.
In the window where you need to open other tabs are often open with another random profile.
The problem occurs when you open a new tab and clicking on the link that opens a new tab.

**Comment by hultmann** [comment]
@yazhog Can you provide a step by step process to reproduce the bug? (e.g. start Firefox, open profile 2, open website X, click link etc)

**Comment by yazhog** [comment]
2 windows of firefox, each window work in two tabs.

start firefox (window1)
select profile1
work in tab1 on website X, click link - open tab2 on website Y. 
close tab2, click link(on tab1) - open tab2 on website Y, etc... 
Works good.

open new window of firefox (window2)
select profile2
work in tab1 on website X, click link - open tab2 on website Y. 
close tab2, click link(on tab1) - open tab2 on website Y, etc...
Sometimes a tab2 is opened with the profile1

when work begins in two windows, the second tab is often not open to the profile, which work in this window.

the problem is not always detected.
sometimes a new tab opens with the wrong profile only once in the first time.
sometimes the problem appears repeatedly in each window.
The second tab is opened with random profile each time you open.
In the first window, there is a problem, too.

I hope you understand me.

**Comment by M4CC** [comment]
It's very simple to explain:
1. Open Firefox on the default tab, create new tabs at will, every tab will start on the default profile;
2. Open a new Profile tab on Firefox, the first tab will be assigned to that profile and when you create a second new tab it assigns correctly to that profile.
3. Open a third, fourth, etc. new tab on that Profile and they will all be assigned to the default profile on the original window (bugged behaviour).
4. Open a third new Profile and it will have the same behaviour as well as all the other window profiles that you open after it.

How could one help troubleshoot this further?

Thanks!

**Comment by M4CC** [comment]
Thank you Hultmann!

3.2.1b1 fixed this issue:
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by hultmann** [comment]
@yazhog Are you using Window Mode? It seems it is not the same bug @M4CC is referring to.

**Comment by yazhog** [comment]
I tried both modes.
problem occurs in both modes.
all actions in the windows are made using imacros

Two of the browser window.
each with a single tab.

imacros script in every window opened the second tab, which should work with the same profile as the first tab in the window. but sometimes in the second tab opens a different profile.

problem possible imacros
It is I think different processes opening the second tab in the window and multfoks it does not understand it.

for a long time watching the work imacros with multifox and came to the conclusion that if you watch the open window, then it does not show a problem. while the window that works in the background tab opens with no correct profile.

I hope you understand me.
