### ISSUE TITLE
Yahoo content not loading properly unless I use the default profile

### ISSUE THREAD

**Issue by lazlot** [hultmann/multifox#229]
I have a profile called "Yahoo". When I open my browser I have this profile loading by default. For the most part everything works great but for some reason there are a few Yahoo news pages that do not load the content properly. 

For example, on this page the video, the comments...and the links to other news stories at the bottom of the page do not load unless I switch multifox to the default profile: https://goo.gl/voHzrY

**Comment by higado2** [comment]
Hello! I've recently (starting Oct 26) have been experiencing trouble with yahoo too! For me, it's yahoo mail specifically. It works fine on the default profile, but on Profile two (my other yahoo account), none of the "buttons" work! As such I can't reply, delete or move on to the next email. Perhaps an update to Firefox broke something?

**Comment by richardjay** [comment]
i have same problem.  yahoo mail doesnt work anymore under multifox.  it was my sole reason to get multifox.  multifox is now useless from my perspective.  please fix asap!

**Comment by hultmann** [comment]
Apparently, it is a one-line fix. At least for the bug described by lazlot. Not sure about Yahoo Mail.

P.S. please note Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).

However, I'll try to keep Multifox working until e10s reaches release (Firefox 50? 60?).

**Comment by richardjay** [comment]
so who is going to make the fix?

---

On Thu, 11/5/15, Jeferson Hultmann notifications@github.com wrote:

 Subject: Re: [multifox] Yahoo content not loading properly unless I use the default profile (#229)
 To: "hultmann/multifox" multifox@noreply.github.com
 Cc: "richardjay" rich32323@yahoo.com
 Date: Thursday, November 5, 2015, 4:00 PM

 Apparently, it is a one-line fix.
 At least for the bug described by lazlot. Not sure about
 Yahoo Mail.

 P.S. please note Multifox is not being developed anymore
 due to deprecation
 of XPCOM extensions.

 However, I'll try to keep Multifox working until e10s
 reaches release (Firefox 50? 60?).

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by hultmann** [comment]
me (I'm currently making Multifox work on Firefox 44)

**Comment by richardjay** [comment]
thanks so much! it is great when it works...

will you let us know when you have done that so we can try using it again?

**Comment by hultmann** [comment]
Please try 3.2.2beta2
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/beta

**Comment by higado2** [comment]
I tried 3.2.2beta2! It's working again! THANK YOU!!!! Yahoo Mail buttons are working now! I can delete emails, and move to the next email again! Joy.

**Comment by richardjay** [comment]
can you tell me how to install this version? I am doing something wrong...

---

On Sat, 11/7/15, higado2 notifications@github.com wrote:

 Subject: Re: [multifox] Yahoo content not loading properly unless I use the default profile (#229)
 To: "hultmann/multifox" multifox@noreply.github.com
 Cc: "richardjay" rich32323@yahoo.com
 Date: Saturday, November 7, 2015, 5:57 PM

 I tried 3.2.2beta2! It's
 working again! THANK YOU!!!! Yahoo Mail buttons are working
 now! I can delete emails, and move to the next email again!
 Joy.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by higado2** [comment]
Follow the link above, then hover your mouse over "Version 3.2.2beta2" , a yellow (?) button will magically appear on the right that says "+ Add to FireFox"

**Comment by richardjay** [comment]
my version was 41.  so i had to upgrade firefox to download. then it works!  yAY!
THANKS SO MUCH! 
richard

**Comment by hultmann** [comment]
Great! My work here is done.

**Comment by lazlot** [comment]
Thank you for taking the time to fix this.

**Comment by lazlot** [comment]
So will the deprecation of XPCOM extensions prevent this type of plugin from being possible in the future?

**Comment by hultmann** [comment]
Yes (probably).

(For Multifox specifically, it seems Mozilla is planning a Multifox-like feature for Firefox.)

**Comment by richardjay** [comment]
i want to echo lazlot's expression of gratitude for your time to fix this.  it makes a big difference in usability.  thank you!
