### ISSUE TITLE
Multifox 2b3: Address bar item is showing in all tabs until I make a first login

### ISSUE THREAD

**Issue by strel** [hultmann/multifox#39]
I'm trying the latest beta in FF 9.0a1 32bit on W7, and since I start the browser it shows Multifox address bar item widely opened with Multifox beta message in all windows and tabs until I make a first login in any site, after that it only shows Multifox item in the adress bar of the tabs where that site is loaded showing the login ID.

Keep up the good the work, this extension rocks.

**Comment by hultmann** [comment]
Already filed as https://github.com/hultmann/multifox/issues/38 :-)

**Comment by Drugoy** [comment]
I don't actually think it's a dupe of #38.
It's a different issue.
Here was described an issue of the shown "multifox" button appearing in every tab, and the issue I filed is about getting logged out from _some_ sites where I was logged in. So in my case I actually lose cookies for the sites with a checkbox "remember me" every time I restart my browser, while this bug is not causing much trouble to me (I have a big monitor, and this 100x16 px button in the address bar doesn't bother me much.

**Comment by Drugoy** [comment]
Or you may be right that it is the same bug, and these are just some more symptoms, which I didn't notice when I filed my bug.

p.s.: yeah, seems so.

**Comment by hultmann** [comment]
As far as I understand it, bugs #38 and #39 are "Firefox 9 is removing Multifox cookies when restarting" (that's why Multifox button appears, there are no Multifox cookies).

**Comment by Drugoy** [comment]
Probably. I don't know the inner mechanics of your extension yet and was not sure when did this button appear.
So could you fix it, please?

**Comment by hultmann** [comment]
Yes, but I won't be able to start up development again until September/October.

**Comment by Drugoy** [comment]
The bug is still present in 2b4
