### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by IceDBear** [hultmann/multifox#49]
Hi,

I love multifox (2.0b), me and my wife use it primarily because of our multiple google accounts. But it's not perfect, I have the following issues/ideas:

A) whitelist / blacklist
Sadly, multifox breaks a few pages for me:
- feedly.com, that page uses google logins, can't login with multifox enabled (opens a popup for login, looses cookie?)
- various little issues with battlelog.battlefield.com (server browser / stats page for Battlefield 3) The game is launched from the browser and in some cases synching between the game client ant the web page doesn't seem to work.
- paying with paypall is impossible with multifox enabled (haven't tried with 2.0b4)

All of this could be fixed with blacklisting pages  or, preferably, whitelisting. I am aware that you have no plans to include this feature, but I beg you to reconsider.

B) default login for webpages
youtube is the main reason for this. I use youtube with only one of my google accounts, an that account is not my primary. I have a google+ tab always open on my primary account, and when I click any youtube link (on any page), it opens youtube with my primary mail. I always have to manualy switch to the correct account so I can comment, thumbs up/down, etc. A default login would come in handy.

**Comment by andrzej-r** [comment]
Just adding "me too". For me (B) is the single biggest problem with Multifox 2.0b. I don't know what is the best way to solve it but I'd like the solution to be as robust, reliable and easy to use as the behavior of Multifox 1.3. In Multifox 1.3 the identity never changes and it is assigned per window rather than per service. It's also trivial to figure out which set of cookies is in use (particularly important for websites pulling cookies from multiple domains).

**Comment by Drugoy** [comment]
Do never fill in your wishlists into an issue.
File only one feature request or one bug report per one issue in a bugtracker.

**Comment by Drugoy** [comment]
@hultmann I request to close this issue in favor of opening 2 new proper ones.

**Comment by hultmann** [comment]
yep, there are bugs filed on similar issues.
