### ISSUE TITLE
An anonymous connection should remain anonymous during a page's lifetime

### ISSUE THREAD

**Issue by a-raccoon** [hultmann/multifox#76]
Having just installed 2b5, I encountered some strange behavior.

After restarting firefox, both my existing pinned Facebook tabs were logged onto the same account (not unexpected after an update) so I logged out of Facebook in both tabs.

There being no existing accounts yet, there was nothing from Multifox in the address bar on the first tab.  I logged into my first account on Facebook

On the next tab, I saw an "&lt;IGNOREME&gt;" tag from Multifox in the address bar.  I ignored it, and logged into Facebook with my second account email/password.  The page loaded and presented me with the news feed of my first Facebook account while showing the email address of my second facebook account in the Multfox tag in the address bar. (unusual)

So I selected the account from the Multifox address bar tag, selected "removed" from the menu, and this time it said "New Account" instead of  "&lt;IGNOREME&gt;".  I was able to then log into Facebook with my second account as expected.

Hope I provided the details you need to figure it out.

**Comment by hultmann** [comment]
You will see [IGNOREME] when a random page loads a logged in element (e.g. facebook/twitter widget).

Your second facebook tab starts anonymous. The bug here is it will use an id as soon it exists (i.e it will mix anonymous/logged in state).

**Comment by kngdogbrt** [comment]
I get the "<IGNOREME>" tag when I access sites that uses Facebook for authentication. An example is the Castle Age Facebook game direct access site at http://web3.castleagegame.com/castle_ws/index.php. It logs me in correctly as long as go from a Facebook page logged in as that user but switching users is not possible.

**Comment by gkats2002** [comment]
I noticed the exact same thing, in the exact page and until two days ago i did not have any problems and was workig on 2b5. It seems that when loading the page with a greasemonkey script loading (ca-tools) it does not work as it did previously, if i stop the script from loading, it works OK. But the question here is why it started happening. I had noticed a warning that it might confuse accounts, but i dont remember if i clicked something causing the <IGNORE ME> to appear on that particular page. Could it be possible that there is somewhere a setting to allow this page again to load correctly ?

**Comment by gkats2002** [comment]
For those that have problem with the castle age page, when it loaded, i went back one page from the browser button, and it tries to load again, before that happens, i press the home page in facebook amd then if i load the game again, it does not show the <IGNORE ME> but the user account, so try it.

**Comment by Drugoy** [comment]
@hultmann 
but why not hide this <IGNOREME>, since it is completely useless?
This style
<code>label[value="<IGNOREME>"] { display: none !important; }</code>
does the trick, but since it hides the lowest (in the DOM-tree meaning) element (which is "label") - it leaves some garbage behind (although it is hard to notice that - it is still there).

I also would like to ask, why did you add so many needless items to DOM?

You've added
#multifox-icon - currently it is not used for anything useful.
#multifox-icon > box - this one is completely needless: it just has 1 dom node: [tooltiptext="Multifox 2 (BETA)"]
#multifox-icon > box > hbox - it has some styles applied, but since it contains nothing - it's needless.
#multifox-icon > box > hbox > #multifox-icon-stat-icon - you could combine it with the next element.
#multifox-icon > box > hbox > label - you could have stored everything you store here ([crop="end"], [value="something"] and [style="some css style"]) in it's initial ancestor hbox[id="multifox-icon"].

Thus, you would have injected only 1 element to the DOM-tree instead of 5.
And it would help fixing this issue #76 completely, not partially like the code I suggested does.

**Comment by hultmann** [comment]
> but why not hide this , since it is completely useless?

It will be used in the next beta.

> I also would like to ask, why did you add so many needless items to DOM?

As far I can remember (from a few years ago), all elements are necessary to preserve the current layout.

> And it would help fixing this issue #76 completely, not partially like the code I suggested does.

#76, this bug? To fix it I will need to keep a list of all TLDs accessed by the tab (the icon is actually a side effect of the real bug).
